package isdcm.webapp.soapserver.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2021-04-02T00:44:40.570+02:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "VideoPortService",
                  wsdlLocation = "file:/C:/Users/mantu/IdeaProjects/webApp1/src/main/resources/wsdl/Video.wsdl",
                  targetNamespace = "http://ws.soapserver.isdcm")
public class VideoPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.soapserver.isdcm", "VideoPortService");
    public final static QName VideoPortSoap11 = new QName("http://ws.soapserver.isdcm", "VideoPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("src/main/resources/wsdl/Video.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VideoPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "src/main/resources/wsdl/Video.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VideoPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VideoPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VideoPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VideoPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VideoPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VideoPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns VideoPort
     */
    @WebEndpoint(name = "VideoPortSoap11")
    public VideoPort getVideoPortSoap11() {
        return super.getPort(VideoPortSoap11, VideoPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VideoPort
     */
    @WebEndpoint(name = "VideoPortSoap11")
    public VideoPort getVideoPortSoap11(WebServiceFeature... features) {
        return super.getPort(VideoPortSoap11, VideoPort.class, features);
    }

}
